### ISSUE TITLE
Saving 3 inserts in one post route

### ISSUE THREAD

**Issue by duard** [mesaugat/express-api-es6-starter#18]
How can I insert record in 3 tables (mysql) in one post route ?

I have 3 tables, 

table A - id

table B id, a_id
table C id, a_id

I need to create the record on table A and them pass his id to the another tables records.

**Comment by duard** [comment]
It works, but I want  to handle errors 

```
return new RecordPessoa({ tipo_documento: record.tipo_documento })
    .save()
    .then(pessoa => {
      console.log(`PESSOA ${pessoa}`);

      return new Record({ pessoa_id: pessoa.id })
        .save()
        .then(record => record.refresh());
    });

```

**Comment by mesaugat** [comment]
If you want to do multiple queries and save records to different tables take a look at transactions. See the example here: http://bookshelfjs.org/#Bookshelf-instance-transaction

It is also handling the errors.

**Comment by duard** [comment]
How can I use transactions in my services ? I got error transaction is not a function when I try it

```
import Bookshelf from 'bookshelf';
...
/**
 * Create new record.
 *
 * @param  {Object}  record
 * @return {Promise}
 */
export function createRecord(record) {
  const tipoDocumento = record.tipo_documento;
  console.log(`createRecord ${tipoDocumento}`);
  Bookshelf.transaction(function(t) {
    console.log('just trying transaction here ===>' + t);
  })
    .then(function(library) {
      console.log(library.related('books').pluck('title'));
    })
    .catch(function(err) {
      console.error(err);
    });
}
...
2017-11-18T12:17:40.196Z - info: Server started at http://127.0.0.1:8848
==> {"tipo_documento":0,"cpf":"53563454353543","nascimento":"30/02/1890","nome_1":"Carlos Eduardo","nome_2":"Matias de Pereiras"}
createRecord 0
2017-11-18T12:17:42.932Z - error:  TypeError: _bookshelf2.default.transaction is not a function
    at Object.createRecord (/home/duard/DevTest/api-mysql/src/modules/pessoas/clientes/clienteService.js:43:13)
    at /home/duard/DevTest/api-mysql/src/modules/pessoas/clientes/clienteCtrl.js:33:6
    at Layer.handle [as handle_request] (/home/duard/DevTest/api-mysql/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/duard/DevTest/api-mysql/node_modules/express/lib/router/route.js:137:13)
    at /home/duard/DevTest/api-mysql/src/modules/pessoas/clientes/clienteValidator.js:26:17
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
POST /api/clientes 500 32.031 ms - 47



```

**Comment by mesaugat** [comment]
Get your bookshelf instance from [db.js](https://github.com/mesaugat/express-api-es6-starter/blob/master/src/db.js) just like in the models.

```js
import bookshelf from '../db'
```

**Comment by duard** [comment]
Sorry, i did that after ask you.  Thanks man, and sorry again.
